<?PHP

$form = new Com_Wizard_Form();
$form->title = "Formulario BLogs";

$form->addAction("floppy-disk", "Guardar", null, "document.getElementById('saveForm').click();");
$form->addAction("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . "/Admin/Blog");

$form->addTab("Idioma por Defecto (" . $this->languages[0]->LanName . ")", "", true);

$control = new Com_Wizard_Form_Control_Hidden();
$control->name = "Language";
$control->default = $this->Language;
$form->add($control);

$control = new Com_Wizard_Form_Control_Select();
$control->name = "Color";
$control->label = "Color";
$control->default = $this->Color;
$control->required = true;
$control->addItem('slide-gray', 'Gris');
$control->addItem('slide-black', 'Negro');
$control->addItem('slide-yellow', 'Amarillo');
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Title";
$control->label = "Titulo";
$control->default = $this->Title;
$control->length = 50;
$control->required = true;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Alias";
$control->label = "Alias";
$control->default = $this->Alias;
$control->length = 50;
$control->required = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_Text();
$control->name = "Description";
$control->label = "Descripcion";
$control->default = $this->Description;
$control->required = true;
$control->rows = 3;
$control->addParameter("style ", "height:120px;");
$form->add($control);

$control = new Com_Wizard_Form_Control_CKEditor();
$control->name = "Content";
$control->label = "Contenido";
$control->default = $this->Content;
$form->add($control);

$control = new Com_Wizard_Form_Control_File();
$control->name = "Logo";
$control->label = "Logo Big";
$control->default = $this->Logo;
$control->required = true;
$control->isImage = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_File();
$control->name = "Image";
$control->label = "Logo Normal";
$control->default = $this->Image;
$control->required = false;
$control->isImage = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_Select();
$control->name = "Status";
$control->label = "Estado";
$control->default = $this->Status;
$control->required = true;
$control->addItem('1', 'Habilitado');
$control->addItem('0', 'Bloqueado');
$form->add($control);

$form->render();
