<?PHP

$db = new Entities_Relations();
$grid = new Com_Wizard_Grid();
$grid->title = "Listado Relaciones";
$grid->setIdField("RelId");
$grid->setLanField("RelLanId");
$grid->setQuery($db->getListWithLanguages());
$grid->setAlias(array("LanName" => "Idioma", "RelProId" => "Proyecto", "Cliente" => "RelCliId", "RelStatus" => "Estado"));
$grid->setFilters(array("RelProId" => get('RelProId')));

$toolBar = new Com_Wizard_ToolBar();
$toolBar->add("plus", "Nuevo", Com_Helper_Url::getInstance()->urlBase . '/Admin/Relations/Add');
$toolBar->add("search", "Filtrar", null, "showHide('.filters')");
$toolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . '/Admin');
$grid->setToolBar($toolBar);

$grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Relations/Edit/lan/_LANGUAGE_/id/_ID_');
$grid->addAction("trash", "Eliminar", null, "confirm('Esta seguro de eliminar el registro?')?location.href='" . Com_Helper_Url::getInstance()->urlBase . '/Admin/Relations/Delete/id/_ID_' . "':'';");

$grid->customField("RelStatus", array("value" => array('1' => 'Habilitado', '0' => 'Bloqueado')));

$grid->render();
