<?PHP

$db = new Entities_Blog();
$grid = new Com_Wizard_Grid();
$grid->title = "Listado Blogs";
$grid->setIdField("BloId");
$grid->setLanField("BloLanId");
$grid->setQuery($db->getListWithLanguages());
$grid->setAlias(array("LanName" => "Idioma", "BloDate" => "Fecha", "BloTitle" => "Titulo", "BloUrl" => "Url", "BloStatus" => "Estado"));
$grid->setFilters(array("BloTitle" => get('BloTitle')));

$toolBar = new Com_Wizard_ToolBar();
$toolBar->add("plus", "Nuevo", Com_Helper_Url::getInstance()->urlBase . '/Admin/Blog/Add');
$toolBar->add("search", "Filtrar", null, "showHide('.filters')");
$toolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . '/Admin');
$grid->setToolBar($toolBar);

$grid->addAction("list-alt", "Items", Com_Helper_Url::getInstance()->urlBase . '/Admin/Articles/Index/lan/_LANGUAGE_/idBlog/_ID_');
$grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Blog/Edit/lan/_LANGUAGE_/id/_ID_');
$grid->addAction("trash", "Eliminar", null, "confirm('Esta seguro de eliminar el registro?')?location.href='" . Com_Helper_Url::getInstance()->urlBase . '/Admin/Blog/Delete/id/_ID_' . "':'';");

$grid->customField("BloStatus", array("value" => array('1' => 'Habilitado', '0' => 'Bloqueado')));
$grid->customField("BloDate", array("dateFormat" => "d/m/Y H:i:s"));

$grid->render();
