<div class="background">
    <img src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/fondo3.jpg">
</div>
<div class="container forBlockw">
    <div class="title">
        <?PHP
        echo $this->page->PagName;
        ?>
    </div>
    <div class="clearfix"></div>
    <div class="text">
        <?PHP
        echo $this->page->PagContent;
        ?>
    </div>

    <div class="image">
        <img src="<?PHP echo Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?PHP echo $this->page->PagImage; ?>">
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
</div>
<div class="clearfix"></div>
