<?PHP

$form = new Com_Wizard_Form();
$form->title = "Formulario Autores";

$form->addAction("floppy-disk", "Guardar", null, "document.getElementById('saveForm').click();");
$form->addAction("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . "/Admin/Clients");

$control = new Com_Wizard_Form_Control();
$control->name = "Name";
$control->label = "Nombre";
$control->default = $this->Name;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Email";
$control->label = "Email";
$control->default = $this->Email;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control_Select();
$control->name = "Gender";
$control->label = "Genero";
$control->default = $this->Gender;
$control->required = true;
$control->addItem('Femenino', 'Femenino');
$control->addItem('Masculino', 'Masculino');
$form->add($control);

$control = new Com_Wizard_Form_Control_Date();
$control->name = "Birthday";
$control->label = "Fecha de nacimiento";
$control->default = $this->Birthday;
$control->required = true;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Country";
$control->label = "Pais";
$control->default = $this->Country;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control_File();
$control->name = "Image";
$control->label = "Imagen";
$control->default = $this->Image;
$control->isImage = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_Text();
$control->name = "Resume";
$control->label = "Resumen";
$control->default = $this->Resume;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control_Password();
$control->name = "Password";
$control->label = "Contraseña";
$control->default = $this->Password;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control_Select();
$control->name = "Status";
$control->label = "Estado";
$control->default = $this->Status;
$control->required = true;
$control->addItem('1', 'Habilitado');
$control->addItem('0', 'Deshabilitado');

$form->add($control);

$form->render();
