
<!DOCTYPE html>
<html class="blog-page">
    <head lang="es">
        <meta charset="UTF-8">
        <meta property="fb:admins" content="750124831"/>
        <meta property="fb:admins" content="771300525"/>
        <title><?PHP echo $this->blog->BloTitle; ?></title>


        <?PHP
        Com_Helper_Style::getInstance()->addFile("Public/bootstrap.css")
                ->addFile("Public/bootstrap-theme.min.css")
                ->addFile("Public/font-awesome.css")
                ->addFile("Public/bootstrap-modal-carousel.min.css")
                ->addFile("Public/main.css");
        echo Com_Helper_Style::getInstance();
        ?>
    </head>
    <body>

        


</body>
</html>