<!DOCTYPE html>
<html lang="es">
    <head>
        <title><?PHP echo $this->translator->pageTitle; ?></title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="robots" content="none">
        <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;">  
        
    </head>
    <body>
        <div class="error">
            <div class="image">
                <span class="icon-Heifer"></span>
            </div>
            <div class="message">
                <?PHP echo $this->translator->errorMessage; ?>
            </div>
            <div class="button">
                <a href="<?PHP echo Com_Helper_Url::getInstance()->urlBase; ?>"><?PHP //echo $this->translator->errorButton; ?></a>
            </div>
        </div>
    </body>
</html>